name: build cv 

on:
  push:
    branches:
      - main
  workflow_dispatch: # allow manual triggering

jobs:
  build:
    runs-on: ubuntu-22.04

    permissions:
      contents: write   
      packages: write   

    steps:
    - name: checkout repository
      uses: actions/checkout@v3

    - name: cache teX live
      id: cache-texlive
      uses: actions/cache@v3
      with:
        path: /usr/local/texlive
        key: texlive-${{ runner.os }}-${{ hashFiles('main.tex') }}
        restore-keys: |
          texlive-${{ runner.os }}

    - name: install teX live (if not cached)
      if: steps.cache-texlive.outputs.cache-hit != 'true'
      run: sudo apt-get update && sudo apt-get install -y texlive-full

    - name: determine new version
      id: get_version
      run: |
        git fetch --tags
        
        # default to v0.0.0 if no tags exist
        latest_tag=$(git tag --sort=-v:refname | head -n 1 || echo "v0.0.0")
        
        major=$(echo $latest_tag | cut -d'.' -f1 | tr -d 'v')
        minor=$(echo $latest_tag | cut -d'.' -f2)
        patch=$(echo $latest_tag | cut -d'.' -f3)
        
        # increment version
        new_patch=$((patch + 1))
        new_version="v${major}.${minor}.${new_patch}"

        echo "new version: $new_version"
        echo "version=$new_version" >> $GITHUB_ENV

    - name: compile laTeX document
      run: make -B  # Forces LaTeX to recompile fully

    - name: create github release
      id: create_release
      uses: actions/create-release@v1.1.4
      with:
        tag_name: ${{ env.version }}
        release_name: "${{ env.version }}"
        body: "automatically generated release."
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: upload pdf to release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: KaplanKyla_CV.pdf
        asset_name: KaplanKyla_CV.pdf
        asset_content_type: application/pdf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
